// script.js
const qaPairs = {
    "bugün çalışıyor musun": "Hayır, bugün çalışmıyorum.",
    "kaç yıldır çalışıyorsun": "10 yıldır.",
    "maaş beklentin nedir": "Enflasyona göre değişir :).",
    "seni neden işe alalım": "İş arayışım yok zaten",
    "keyfin nasıl": "Her zaman iyi",
    "nasılsın": "Her zaman iyi",
    "sen kimsin": "Barış Şeref , peki sen kimsin?",
    "bu siteyi nasıl yaptın": "css, html,js",
    "iş bakıyor musun": "iş arayışım yok",
    "neredesin": "şuan burada",
    "memleketin neresi": "Samsun",
    "ne kadar maaş alıyorsun": "Şirket sırrı :)",
    "nerelisin": "Samsun",
    "memleket": "Samsun",
    "burcun": "Aslan",
    "after effect biliyor musun": "Evet",
    "hangi programları biliyorsun": "After Effect, Blender, Iclone, Css ( Tam hali sitenin içerisinde )",
    "burcun nedir": "Aslan",
    "hangi takımlısın": "Beşiktaş",
    "hangi takımı tutuyorsun": "Beşiktaş",
    "tuttuğun takım": "Beşiktaş",
    "iş arıyor  musun": "iş arayışım yok",
    "iş ister misin": "iş arayışım yok",
    "iş teklif ediyorum": "iş arayışım yok",
    "iş": "iş arayışım yok",
    "işinden memnun musun": "Evet, memnunum",
    "nerede çalışıyorsun": "Yurtiçi Kargo",
    "ne kadar maaş veriyorlar": "Şirket sırrı :)",
    "nasıl bir insansın": "İyi derler genelde",
    "hangi okuldan mezun oldun": "Ankara Üni.",
    "nerede yaşıyorsun": "istanbul",
    "telefon": "önce mail atın: baris.seref@gmail.com",
    "sana nasıl ulaşabilirim": "baris.seref@gmail.com",
    "telefon numaran": "önce mail atın: baris.seref@gmail.com",
    "üniversite mezuniyeti": "Ankara Üniversitesi Radyo Televizyon ve Sinema",
    "Üniversite mezuniyetin nedir": "Ankara Üniversitesi Radyo Televizyon ve Sinema",
    "aktif iş arayışı durumu": "Hayır, aktif iş arayışım yok",
    "iş arayor musun": "Hayır, aktif iş arayışım yok",
    "iş teklifi etsem kabul eder misin": "Hayır, aktif iş arayışım yok",
    "çalışma süresi": "10 yıl çalışma deneyimim var",
    "bildiğiniz programlar": "After Effect, Blender, Iclone, Css ( Tam hali sitenin içerisinde )",
    "freelance iş durumu": "Freelance iş durumu projelere bağlı olarak değişebilir",
    "telefon numarası": "Telefon numaram için lütfen önce e-posta ile iletişime geçin",
    "yurtdışında çalışır mısın": "Yurt dışında çalışma olasılığını değerlendirebilirim",
    "mezun olduğunuz üniversite ve bölüm": "Ankara Üniversitesi Radyo Televizyon ve Sinema",
    "çalışma deneyiminiz hakkında detaylar": "10 yıldır medya sektöründe çeşitli projelerde çalıştım.",
    "hangi programlama dillerini biliyorsunuz": "CSS, HTML, JavaScript",
    "neden freelance çalışıyorsunuz": "Genelde freelance çalışmıyorum",
    "hangi ülkelerde çalışmayı düşünebilirsiniz": "Yurt dışında çalışma olasılığını değerlendirebilirim",
    "iş dışındaki hobileriniz nelerdir": "Fotoğrafçılık, seyahat etmek, satranç",
    "en son hangi projede çalıştınız": "Son projem bir reklam kampanyasıydı.",
    "referanslarınız hakkında bilgi verebilir misiniz": "Referanslarımı talep etmeniz durumunda iletebilirim.",
    "referanslarınız kimdir": "Referanslarımı talep etmeniz durumunda iletebilirim.",
    "en iyi beceriniz nedir": "Animasyon ve video prodüksiyonu",
    "kendinizi 3 kelimeyle nasıl tanımlarsınız": "Yaratıcı, disiplinli, öğrenmeye açık",
    "gelecekteki kariyer hedefiniz nedir": "Yönetmenlik yapmak istiyorum",
    "hangi projelerde çalışmayı seversiniz": "Sinema projeleri beni en çok heyecanlandırıyor.",
    "neden bu sektörü seçtiniz": "Çocukluğumdan beri medya ve sanatla ilgileniyorum.",
    "en zorlu proje deneyiminiz nedir": "Bir belgesel projesinin düşük bütçesi nedeniyle zorlu bir deneyim yaşadım.",
    "takım çalışmasında ne kadar etkili olduğunuzu düşünüyorsunuz": "Takım çalışmasında uyumlu ve işbirlikçiyim.",
    "en sevdiğiniz projeniz hangisi": "Her projemi severim",
    "yaratıcılığınızı nasıl beslersiniz": "Yeni teknolojileri ve sanat akımlarını takip ederek beslerim.",
    "en son hangi eğitimi aldınız": "Python üzerineydi",
    "çalışma saatleriniz hakkında nasıl bir tercihiniz var": "Esnek çalışma saatlerini tercih ederim.",
    "başkalarıyla iletişim kurarken ne kadar etkili olduğunuzu düşünüyorsunuz": "İyi bir iletişimci olduğumu düşünüyorum.",
    "bir proje yöneticisi olarak deneyiminiz nedir": "Birçok projeyi başarıyla yönettim.",
    "kreatif bir problem çözme örneği verebilir misiniz": "Bu soru cevap kısmı, sorunuzu yanıtlamıştır diye düşünüyorum",
    "yeni beceriler öğrenmeye ne kadar açıksınız": "Yeni beceriler öğrenmeye her zaman açığım.",
    "en sevmediğiniz proje deneyiminiz nedir": "Projelerden daha çok revizeleri sevmem",
    "hangi sanatçılar veya yönetmenler sizi etkiliyor": "Stanley Kubrick ve Wong kar waii beni etkiliyor.",
    "iyi bir projede ne tür bir rol oynamak istersiniz": "Yaratıcı yönetmen veya animatör olarak rol almak isterim.",
    "iş arkadaşlarıyla uyumlu bir şekilde çalışmayı nasıl sağlarsınız": "Açık iletişim kurarak ve fikirleri paylaşarak uyumu sağlarım.",
    "kariyerinizde hangi dönüm noktaları oldu": "Bir kısa film festivalinde ödül kazanmak kariyerimin dönüm noktasıydı.",
    "tasarım projelerinde ne kadar deneyiminiz var": "Tasarım projelerinde 5 yıldan fazla deneyimim var.",
    "bir projeyi nasıl yönetirsiniz": "Proje hedeflerini belirler, görevleri planlar ve ekip üyeleriyle iletişimde kalırım.",
    "işte liderlik rolünü nasıl ele alırsınız": "Ekip üyelerini motive eder, yönlendirir ve desteklerim.",
    "müşteri ilişkilerinizi nasıl yönetirsiniz": "İyi iletişim kurarak, müşteri ihtiyaçlarını anlar ve beklentilerini karşılarım.",
    "stresli durumlarla nasıl başa çıkarsınız": "Yürüyüş yaparım genelde",
    "bir projeyi tamamlamak için hangi adımları takip edersiniz": "Araştırma, planlama, üretim ve düzenleme aşamalarını takip ederim.",
    "kendi kendinize öğrenme yeteneğinizi nasıl değerlendirirsiniz": "Yeni konuları öğrenmeye hevesli ve hızlı öğrenen biriyim.",
    "en zorlu tasarım probleminiz nedir ve nasıl çözdünüz": "Bir animasyon projesindeki karmaşık sahneleri çözmek için farklı yaklaşımlar denedim.",
    "projelerinizde hangi adımları önceliklendirirsiniz": "Hedefleri belirlemek, kaynakları planlamak ve takım üyelerini organize etmek önceliğimdir.",
    "geçmişte çalıştığınız zorlu müşteri örneği nedir": "Bir projede sürekli değişen gereksinimlere sahip bir müşteriyle çalıştım.",
    "işte verimliliği nasıl artırırsınız": "İş akışını düzenlemek, zaman yönetimi ve öncelikleri belirlemek verimliliği artırır.",
    "ekip içinde işbirliği nasıl yaparsınız": "Görevleri paylaşmak, fikir alışverişi yapmak ve ekip üyeleriyle iletişimde kalmak işbirliğini sağlar.",
    "çalışma alanınızı nasıl düzenlersiniz": "Düzenli ve temiz bir çalışma alanı yaratmak için sık sık düzenlerim.",
    "çalışmalarınızı nasıl organize edersiniz": "Proje yönetimi araçları kullanarak görevleri ve süreçleri takip ederim.",
    "hangi projelerde daha iyi performans gösterirsiniz": "Animasyon veya hareketli grafik projelerinde daha iyi performans gösteririm.",
    "proje sırasında hangi zorlukları aşmayı başardınız": "Bir proje sırasında bütçe ve zaman kısıtlamalarını aşarak başarıya ulaştım.",
    "ekip üyeleriyle anlaşmazlık durumunda nasıl davranırsınız": "Anlaşmazlık durumlarında açık iletişimle sorunları çözmeye çalışırım.",
    "bir projede lider olarak nasıl hareket edersiniz": "Ekip üyelerini motive eder, yönlendirir ve projeyi takip ederim.",
    "bir projeyi nasıl planlarsınız": "Hedefleri belirler, görevleri ayarlar ve projeyi aşamalara bölerim.",
    "müşteri geri bildirimini nasıl ele alırsınız": "Müşteri geri bildirimini dikkate alır, projeyi müşteri beklentilerine göre şekillendiririm.",
    "kendinizi nasıl geliştiriyorsunuz": "Yeni teknikleri öğrenmek ve becerilerimi geliştirmek için online eğitimler alıyorum.",
    "çalışmalarınızı nasıl sergiliyorsunuz": "Web sitemde portföyümü sergiliyorum ve sosyal medya platformlarında paylaşıyorum.",
    "projelerde sıkça karşılaştığınız zorluklar nelerdir": "Bütçe kısıtlamaları ve değişken projelerde karşılaştığım zorluklar arasında.",
    "hangi projelerde daha etkili olduğunuzu düşünüyorsunuz": "Animasyon veya hareketli grafik projelerinde daha etkili olduğumu düşünüyorum.",
    "bir projenin başarı kriterleri nelerdir": "Projenin hedefleri, müşteri beklentileri ve kalite standartları başarı kriterlerini oluşturur.",
    "hangi projelerde yaratıcılığınızı en iyi şekilde kullanıyorsunuz": "Reklam kampanyaları veya sanatsal projelerde yaratıcılığımı en iyi şekilde kullanıyorum.",
    "bir projeyi tamamlamak için nasıl bir süreç takip edersiniz": "Araştırma, planlama, üretim, düzenleme ve teslim aşamalarını takip ederim.",
    "kariyerinizde en gurur duyduğunuz an nedir": "Bir belgesel projesiyle ilgili olarak bir ödül kazandığım anı en çok gurur duyduğum an olarak sayabilirim.",
    "hangi projelerde daha iyi sonuçlar elde ediyorsunuz": "Reklam kampanyaları veya tanıtım videolarında daha iyi sonuçlar elde ediyorum.",
    "proje süresini nasıl yönetiyorsunuz": "Takvim oluşturmak, görevleri planlamak ve süreçleri takip etmek süreyi yönetmemi sağlar.",
    "iş arkadaşlarınızla nasıl iletişim kurarsınız": "Açık ve net iletişim kurarak iş arkadaşlarımla etkili bir şekilde iletişim kurarım.",
    "bir projede karşılaştığınız zorlu bir durumu nasıl çözdünüz": "Zorlu bir bütçe kısıtlamasını deneyimlerimi ve kaynakları etkili bir şekilde kullanarak çözdüm.",
    "başkalarına nasıl ilham veriyorsunuz": "Yaratıcı projelerim ve sorun çözme becerilerimle başkalarına ilham vermeye çalışıyorum.",
    "bir projeyi nasıl planlarsınız": "Proje hedeflerini belirler, görevleri planlar ve takip ederim.",
    "kendinizi nasıl motive edersiniz": "Başarılarımdan ve ilerlememden motive olurum.",
    "proje sırasında iş arkadaşlarınızla yaşadığınız anlaşmazlıkları nasıl çözersiniz": "Açık iletişim ve uzlaşma yolunu seçerek anlaşmazlıkları çözmeye çalışırım.",
    "çalışmalarınızı nasıl düzenliyorsunuz": "Takvimler ve görev listeleri kullanarak işleri düzenlerim.",
    "yaratıcı bir projeyi nasıl ele alırsınız": "Fikir üretimi, araştırma ve konsept oluşturma aşamalarını takip ederek yaratıcı projelere yaklaşırım.",
    "bir projede nasıl liderlik yaparsınız": "Ekip üyelerine yönlendirme yapar, görevleri koordine eder ve projeyi yönetirim.",
    "bir projede müşteri beklentilerini nasıl karşılarsınız": "Müşteriyle düzenli iletişim kurar ve geri bildirimleri dikkate alarak projeyi şekillendiririm.",
    "bir projede takım üyeleri arasındaki işbirliğini nasıl teşvik edersiniz": "Fikir paylaşımını ve bilgi alışverişini teşvik ederim, sorunları birlikte çözmeye çalışırım.",
    "kariyerinizdeki en büyük başarınız nedir": "Bir reklam kampanyası projesinde liderlik yaparak %30'luk bir artış elde etmek en büyük başarım.",
    "çalışma disiplininizi nasıl sürdürüyorsunuz": "Takvim ve zaman yönetimi araçları kullanarak disiplinli çalışmayı sürdürüyorum.",
    "bir projede ekip üyeleri arasındaki anlaşmazlıkları nasıl çözdünüz": "Anlaşmazlıkları yatıştırarak, herkesin görüşünü dinleyerek ve ortak çözümler bulmaya çalışarak çözdüm.",
    "bir projede iş arkadaşlarınızla nasıl uyum içinde çalışırsınız": "Açık iletişim ve işbirliği ile uyum içinde çalışırım.",
    "bir projede nasıl yaratıcı fikirler üretirsiniz": "İlham almak için farklı kaynaklar kullanırım ve farklı bakış açılarına odaklanarak yaratıcı fikirler üretirim.",
    "proje süresince nasıl motive kalırsınız": "Hedeflere odaklanarak, ilerlememi gözlemleyerek ve başarılarımdan motive kalırım.",
    "kariyerinizde karşılaştığınız en büyük zorluk nedir": "Bir projenin son anında gelen büyük bir değişiklik ve zaman kısıtlamasıyla başa çıkmak en büyük zorluklardan biriydi.",
    "bir projede iş arkadaşlarınızla nasıl işbirliği yaparsınız": "Görevleri paylaşmak, fikirleri almak ve vermek ve iletişimde kalarak işbirliği yaparım.",
    "proje sonuçlarını nasıl analiz edersiniz": "Hedeflere ne kadar yaklaşıldığını ve projenin başarısını analiz ederim.",
    "yeni projelere nasıl ilham alırsınız": "Sanat, teknoloji ve sektör trendleri gibi kaynaklardan ilham alarak yeni projeler üretirim.",
    "bir projeyi nasıl organize edersiniz": "Hedefleri ve görevleri belirler, takım üyeleri arasında koordinasyon sağlar ve süreci takip ederim.",
    "kariyerinizde öğrendiğiniz en önemli ders nedir": "Esnek olmanın ve değişen şartlara uyum sağlamanın önemli olduğunu öğrendim.",
    "bir projeyi nasıl planlarsınız": "Projenin hedeflerini ve milestonelarını belirler, görevleri ve süreci planlarım.",
    "çalışmalarınızı nasıl geliştiriyorsunuz": "Yeni beceriler öğrenmek ve projelerde deneyim kazanmak için sürekli çalışmalarımı geliştiriyorum.",
    "bir projede nasıl sorunları ele alırsınız": "Sorunları belirler, analiz eder ve çözmek için ekip üyeleriyle işbirliği yaparım.",
    "bir projeyi nasıl değerlendirirsiniz": "Projenin başarı kriterlerine, hedeflere ve sonuçlara bakarak projeyi değerlendiririm.",
    "kendinizi nasıl motive edersiniz": "Hedeflere ulaşmanın ve projelerdeki ilerlemenin beni motive ettiğini hissederim.",
    "proje sonuçlarını nasıl analiz edersiniz": "Başarı kriterlerini ve hedeflere ne kadar yaklaşıldığını değerlendirerek projenin sonuçlarını analiz ederim.",
    "bir projede iş arkadaşlarınızla uyum içinde nasıl çalışırsınız": "İşbirliği yaparak, fikir paylaşarak ve sorunları birlikte çözerek uyum içinde çalışırım.",
    "kariyerinizdeki en büyük ödül nedir": "Bir proje için kazandığım bir ulusal ödül en büyük kariyer ödüllerimden biriydi.",
    "kendi projelerinizi nasıl organize edersiniz": "Takvimler ve görev listeleri kullanarak projelerimi planlarım ve organize ederim.",
    "bir projede hangi aşamada en iyi performans gösteriyorsunuz": "Projeyi yönlendirdiğim ve tasarım aşamasında en iyi performans gösteriyorum.",
    "bir projeyi nasıl başarıyla yönetirsiniz": "Hedefleri belirler, görevleri planlar, kaynakları yönetir ve süreci takip ederim.",
    "çalışmalarınızı nasıl sürdürülebilir şekilde organize edersiniz": "Çevresel etkileri düşünerek malzemeleri ve kaynakları yönetir ve sürdürülebilir yaklaşımları kullanırım.",
    "kariyerinizdeki en zorlu projeniz nedir": "Bir belgesel projesinde sınırlı zaman ve kaynaklarla çalışmak en zorlu projelerimden biriydi.",
    "bir projede müşteri beklentilerini nasıl yönetirsiniz": "Sık sık iletişim kurarak, geri bildirimi dikkate alarak ve esnek olarak müşteri beklentilerini yönetirim.",
    "kendi projelerinizde nasıl organizasyon kullanıyorsunuz": "Proje yönetimi araçları kullanarak görevleri planlar ve projeleri takip ederim.",
    "bir projede nasıl takım liderliği yaparsınız": "Takım üyelerini yönlendirir, görevleri dağıtır ve projeyi yönetirim.",
    "bir projede iş arkadaşlarınızla nasıl uyum içinde çalışırsınız": "Fikir alışverişi yapar, görevleri paylaşır ve iletişimde kalarak uyum içinde çalışırım.",
    "çalışmalarınızı nasıl sürdürülebilir şekilde planlıyorsunuz": "Sürdürülebilir malzemeleri kullanmayı ve çevresel etkileri azaltmayı planlarım.",
    "bir projeyi nasıl hızlı bir şekilde tamamlarsınız": "Takımı organize eder, görevleri etkili bir şekilde planlar ve süreci hızlandırırım.",
    "kendi projelerinizde hangi aşamada en yaratıcı olursunuz": "Konsept oluşturma aşamasında en yaratıcı olurum.",
    "bir projede iş arkadaşlarınızla nasıl etkili bir iletişim kurarsınız": "Açık ve net iletişim kurarak, fikirleri paylaşarak ve işbirliği yaparak etkili iletişim sağlarım.",
    "bir projede nasıl liderlik yaparsınız": "Ekip üyelerini yönlendirir, görevleri planlar ve projeyi koordine ederim.",
    "kariyerinizdeki en büyük başarınız nedir": "Bir reklam kampanyası projesindeki büyük bir artışla müşteri memnuniyetini artırmak en büyük başarılarımdan biriydi.",
    "kendi projelerinizi nasıl planlıyorsunuz": "Hedefleri belirler, görevleri planlar ve süreci takip ederim.",
    "bir projede iş arkadaşlarınızla nasıl uyum içinde çalışırsınız": "Açık iletişim ve işbirliğiyle uyum içinde çalışırım.",
    "bir projeyi nasıl etkili bir şekilde yönetirsiniz": "Hedefleri belirler, görevleri planlar, kaynakları yönetir ve süreci takip ederim.",
    "çalışmalarınızı nasıl organize ediyorsunuz": "Takvimler ve görev listeleri kullanarak işleri organize ederim.",
    "kariyerinizde en zorlu projeniz nedir": "Sınırlı bütçe ve kaynaklarla karmaşık bir animasyon projesi üzerinde çalışmak en zorlu projelerimden biriydi.",
    "bir projede nasıl işbirliği yaparsınız": "Fikir paylaşımı yapar, görevleri paylaşır ve iletişimde kalarak işbirliği yaparım.",
    "kendi projelerinizi nasıl değerlendiriyorsunuz": "Projelerimi hedeflere ne kadar yaklaşıldığına ve sonuçlara bakarak değerlendiriyorum.",
    "bir projede iş arkadaşlarınızla nasıl uyum içinde çalışırsınız": "Açık iletişim ve işbirliğiyle uyum içinde çalışmaya önem veririm.",
    "bir projeyi nasıl etkili bir şekilde yönlendirirsiniz": "Hedefleri ve görevleri belirler, süreci takip eder ve ekibi yönlendiririm.",
    "kariyerinizdeki en büyük öğrenme deneyimi nedir": "Bir projenin erken aşamalarında müşteri beklentilerini daha iyi anlamayı öğrenmek büyük bir deneyimdi.",
    "kendi projelerinizi nasıl organize ediyorsunuz": "Proje yönetimi araçları kullanarak görevleri planlar ve takip ederim.",
    "bir projede nasıl etkili bir şekilde iletişim kurarsınız": "Açık ve net iletişim kurar, sorunları çözmek için işbirliği yaparım.",
    "bir projeyi nasıl hızlı bir şekilde yönetirsiniz": "Ekip üyelerini motive eder, görevleri etkili bir şekilde planlar ve süreci hızlandırırım.",
    "kariyerinizdeki en büyük öğrenme deneyimi nedir": "Bir projede müşteri beklentilerini daha iyi anlama fırsatı büyük bir öğrenme deneyimiydi.",
    "kendi projelerinizi nasıl değerlendirirsiniz": "Projelerimi hedeflere ne kadar yaklaşıldığına ve sonuçlarına bakarak değerlendiririm.",
    "bir projede nasıl etkili bir şekilde liderlik yaparsınız": "Ekip üyelerini motive eder, görevleri planlar ve projeyi yönlendiririm.",
    "kariyerinizde hangi başarıdan en gurur duyuyorsunuz": "Bir reklam kampanyası projesindeki büyük artışla müşteri memnuniyetini artırmaktan en çok gurur duyuyorum.",
    "kendi projelerinizi nasıl planlıyorsunuz": "Hedefleri belirler, görevleri planlar ve süreci takip ederim.",
    "bir projede nasıl etkili bir şekilde işbirliği yaparsınız": "Açık iletişim ve fikir paylaşımıyla işbirliği yapar, sorunları birlikte çözerim."

    
    // Diğer soru-cevap çiftlerini buraya ekleyebilirsiniz
};


const chatArea = document.getElementById("chatArea");
const userInput = document.getElementById("userInput");
const sendButton = document.getElementById("sendButton");

sendButton.addEventListener("click", () => {
    const userQuestion = userInput.value.trim().toLowerCase();
    if (userQuestion !== "") {
        addMessage(userQuestion, "user");
        generateBotResponse(userQuestion);
        userInput.value = "";
    }
});

function addMessage(message, sender) {
    const messageDiv = document.createElement("div");
    messageDiv.textContent = message;
    messageDiv.classList.add("message", sender);
    chatArea.appendChild(messageDiv);
    chatArea.scrollTop = chatArea.scrollHeight;
}

function generateBotResponse(question) {
    const botResponse = qaPairs[question] || "Üzgünüm, bu sorunun cevabını bilmiyorum.";
    addMessage(botResponse, "bot");
}
